### ISSUE TITLE
remove `jade` from express_router.js

### ISSUE THREAD

**Issue by lowellbander** [dandelion-community/aid-app-monorepo#10]
This is the [only reference](https://github.com/dandelion-community/aid-app-monorepo/search?q=jade) to `jade`
```
app.set('view engine', 'jade');
```

When I pulled a fresh codespace and ran `npm start`, I got the following error:

```
Error: Cannot find module 'jade'
Require stack:
- /workspaces/aid-app-monorepo/node_modules/express/lib/view.js
- /workspaces/aid-app-monorepo/node_modules/express/lib/application.js
- /workspaces/aid-app-monorepo/node_modules/express/lib/express.js
- /workspaces/aid-app-monorepo/node_modules/express/index.js
- /workspaces/aid-app-monorepo/express_router.js
- /workspaces/aid-app-monorepo/src/bin/www
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new View (/workspaces/aid-app-monorepo/node_modules/express/lib/view.js:81:14)
    at Function.render (/workspaces/aid-app-monorepo/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/workspaces/aid-app-monorepo/node_modules/express/lib/response.js:1008:7)
    at /workspaces/aid-app-monorepo/express_router.js:37:7
    at Layer.handle_error (/workspaces/aid-app-monorepo/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/workspaces/aid-app-monorepo/node_modules/express/lib/router/index.js:315:13)
```

**Comment by lowellbander** [comment]
no longer in the repo!
